#ifndef SC_GAMEPAD_IDS_H
#define SC_GAMEPAD_IDS_H

#define SC_MAX_GAMEPADS 8
#define SC_HID_ID_GAMEPAD_FIRST 3
#define SC_HID_ID_GAMEPAD_LAST \
    (SC_HID_ID_GAMEPAD_FIRST + SC_MAX_GAMEPADS - 1)

#endif
